name: Generate API Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'maimai_py/**'
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Generate Static Files
        run: mkdir docs && pip install httpx pdoc && pdoc maimai_py --docformat google -o ./docs
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs --project-name=maimai-py